name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  GCP_ARTIFACT_REGISTRY_REPO: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-actions-pool/providers/PROVIDER_ID"
          service_account: "my-service-account@my-project.iam.gserviceaccount.com"

      - name: Configure gcloud CLI
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set run/region $GCP_REGION

      - name: Build Docker image
        run: |
          docker build -t $GCP_ARTIFACT_REGISTRY_REPO/$GCP_SERVICE_NAME:latest .

      - name: Push to Artifact Registry
        run: |
          docker push $GCP_ARTIFACT_REGISTRY_REPO/$GCP_SERVICE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $GCP_SERVICE_NAME \
            --image $GCP_ARTIFACT_REGISTRY_REPO/$GCP_SERVICE_NAME:latest \
            --platform managed \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --quiet
